@startuml streamVideo-Request
!theme toy
title "streamVideo /api/posts/:postId/stream POST Request"

file "postId.mp4"

json Auth {
    "sub": "",
    "iat": "",
    "exp": ""
}
@enduml
@startuml streamVideo-Response
!theme toy
title "streamVideo /api/posts/:postId/stream POST Response"
@enduml
