@startuml streamVideo-Request
!theme toy
skinparam linetype ortho
title "streamVideo /api/posts/:postId/stream POST Request"

file "postId.mp4"

note left of "postId.mp4"
    Stream of bytes
end note

json Auth {
    "sub": "",
    "iat": "",
    "exp": ""
}

"postId.mp4" --* Auth
@enduml
@startuml streamVideo-Response
!theme toy
title "streamVideo /api/posts/:postId/stream POST Response"
@enduml
