@startuml getReactionsOfPost-Request
!theme toy
skinparam linetype ortho
title "getReactionsOfPost /api/reactions GET Request"

json Data {
    "postId": "",
    "limit": "",
    "offset": ""
}
@enduml
@startuml getReactionsOfPost-Response
!theme toy
skinparam linetype ortho
title "getReactionsOfPost /api/reactions GET Response"

package "reactions.zip" {

    folder "pfps" {
        file "userId-pfp.png"
    }

    json "reactions.json" {
        "reactions": [
            {
                "reactionId": "",
                "postId": "",
                "user": {
                    "userId": "",
                    "username": ""
                },
                "emojiId": ""
            }
        ]
    }

    "reactions.json" --o "pfps"
}
@enduml
