@startuml addCommentToPost-Request
!theme toy
skinparam linetype ortho
title "addCommentToPost /api/comments POST Request"

json Data {
    "postId": "",
    "text": ""
}

json Auth {
    "sub": "",
    "iat": "",
    "exp": ""
}

Data --* Auth
@enduml
@startuml addCommentToPost-Response
!theme toy
title "addCommentToPost /api/comments POST Response"

json Data {
    "commentId": ""
}
@enduml
