@startuml getFolloweesOfUser-Request
!theme toy
skinparam linetype ortho
title "getFolloweesOfUser /api/follows/followees GET Request"

json Data {
    "userId": "",
    "limit": "",
    "offset": ""
}

note bottom of Data 
    By chunks: **limit**, **offset** required.
end note
@enduml
@startuml getFolloweesOfUser-Response
!theme toy
skinparam linetype ortho
title "getFolloweesOfUser /api/follows/followees GET Response"

package "followees.zip" {

    folder "pfps" {
        file "userId-pfp.png"
    }

    json "followees.json" {
        "followees": [
            {
                "followId": "",
                "followee": {
                    "userId": "",
                    "username": ""
                }
            }
        ]
    }

    "followees.json" --o "pfps"
}
@enduml
