@startuml getFriendshipRequestsFromUser-Request
!theme toy
title "getFriendshipRequestsFromUser /api/friendshipRequests/from GET Request"

json Auth {
    "sub": "",
    "iat": "",
    "exp": ""
}
@enduml
@startuml getFriendshipRequestsFromUser-Response
!theme toy
skinparam linetype ortho

title "getFriendshipRequestsFromUser /api/friendshipRequests/from GET Response"

package "friendshipRequests.zip" {

    folder "pfps" {
        file "userId-pfp.png"
    }

    json "friendshipRequests.json" {
        "friendshipRequests": [
            {
                "friendshipRequestId": "",
                "toUser": {
                    "userId": "",
                    "username": ""
                },
                "timestamp": ""
            }
        ]
    }

    "friendshipRequests.json" --* "pfps"
}
@enduml
