@startuml createMusic-Request
!theme toy
skinparam linetype ortho
title "createMusic /api/posts POST Request"

package "post.zip" {
    file "post-cover.png"

    note bottom of "post-cover.png"
        Optional, if not given then a default image will be displayed.
    end note

    json "post.json" {
        "title": "",
        "type": "",
        "description": "",
        ' People who worked on the music project
        "partecipants": [
            {
                ' Optional
                "role": "",
                "userId": ""
            }
        ],
        "tags": []
    }


    note bottom of "post.json"
        Optional fields: **partecipants**, **tags**
    end note
}

json Auth {
    "sub": "",
    "iat": "",
    "exp": ""
}

"post.zip" --* Auth
@enduml
@startuml createMusic-Response
!theme toy
skinparam linetype ortho
title "createMusic /api/posts POST Response"

json Data {
    "postId": ""
}
@enduml


