@startuml likeAContribution-Request
!theme toy
skinparam linetype ortho
title "likeAContribution /api/contributionLikes POST Request"

json Data {
    "contributionId": ""
}

json Auth {
    "sub": "",
    "iat": "",
    "exp": ""
}

Data --* Auth
@enduml
@startuml likeAContribution-Response
!theme toy
title "likeAContribution /api/contributionLikes POST Response"

json Data {
    "contributionLikeId": ""
}
@enduml
