@startuml followUser-Request
!theme toy
skinparam linetype ortho
title "followUser /api/follows POST Request"

json Data {
    "userId": ""
}

json Auth {
    "sub": "",
    "iat": "",
    "exp": ""
}

Data --* Auth
@enduml
@startuml followUser-Response
!theme toy
title "followUser /api/follows POST Response"
json Data {
    "followId": ""
}
@enduml
