@startuml searchPosts-Request
!theme toy
skinparam linetype ortho
title "searchPosts /api/posts GET Request"

json Data {
    "filter": {
        "friendsOnly": "",
        "followeesOnly": "",
        "type": "",
        "tags": []
    },
    "orderBy": "",
    "search": "",
    "limit": "",
    "offset": ""
}

note bottom of Data 
    By chunks: **limit**, **offset** required.
end note

'Optional (only if friendsOnly=true)
json Auth {
    "sub": "",
    "iat": "",
    "exp": ""
}
note right of Auth
    Auth is only necessary if **friendsOnly** = true
end note

Data --o Auth
@enduml
@startuml searchPosts-Response
!theme toy
skinparam linetype ortho
title "searchPosts /api/posts GET Response"

package "posts.zip" {

    folder "pfps" {
        file "userId-pfp.png"
    }

    folder "posts" {
        json "posts.json" {
            "posts": [
                {
                "postId": "",
                "user": {
                    "userId": "",
                    "username": ""
                },
                "title": "",
                "type": "",
                "description": "",
                "timestamp": "",
                ' Optional (only for Music and Video)
                "duration": "",
                "likesCount": "",
                "commentsCount": "",
                "views": "",
                ' Optional (only for articles)
                "contributionsCount": ""
                }
            ]
        }

        note bottom of "posts.json"
            Optional fields: **duration**, **contributionsCount**
        end note

        note left of "posts.json"
            **duration** is only if **type** = Music or Video
            **contributionsCount** is only if **type** = Article
        end note

        folder "covers" {
            file "postId-cover.png"
        }

        "posts.json" --o "pfps"
        "posts.json" --o "covers"
    }
}


@enduml
