@startuml getContribution-Request
!theme toy
title "getContribution /api/contributions/:contributionId GET Request"
@enduml
@startuml getContribution-Response
!theme toy
skinparam linetype ortho
title "getContribution /api/contributions/:contributionId GET Response"

package "contribution.zip" {
    folder "pfps" {
        file "userId-pfp.png"    
    }

    json "contribution.json" {
        "contribution": {
            "contributionId": "",
            "user": {
                "userId": "",
                "username": ""
            },
            "post": {
                "postId": "",
                "title": ""
                ' Cover or not ?
            },
            "title": "",
            "text": "",
            "timestamp": "",
            "applied": "",
            "tags": [],
            "likes": "",
            "dislikes": "",
            "comments": [
                {
                    "commentId": "",
                    "text": "",
                    "timestamp": "",
                    "user": {
                        "userId": "",
                        "username": ""
                    },
                    "likes": "",
                    "dislikes": ""
                }
            ]
        }
    }

    "contributions.json" --o "pfps"
}
@enduml
