@startuml dislikeAContribution-Request
!theme toy
skinparam linetype ortho
title "dislikeAContribution /api/contributionDislikes POST Request"

json Data {
    "contributionId": ""
}

json Auth {
    "sub": "",
    "iat": "",
    "exp": ""
}

Data --* Auth
@enduml
@startuml dislikeAContribution-Response
!theme toy
title "dislikeAContribution /api/contributionDislikes POST Response"

json Data {
    "contributionDislikeId": ""
}
@enduml
