@startuml getCommentsOfUser-Request
title "getCommentsOfUser /api/comments GET Request"


json Data {
    "limit": "",
    "offset": ""
}

note bottom of Data 
    By chunks: **limit**, **offset** required.
end note
@enduml
@startuml getCommentsOfUser-Response
skinparam linetype ortho
title "getCommentsOfUser /api/comments GET Response"

package "comments.zip" {

    folder "pfps" {
        file "userId-pfp.png"
    }

    folder "covers" {
        file "postId-cover.png"
    }

    json "comments.json" {
        "comments": [
            {
                "commentId": "",
                "post": {
                    "postId": "",
                    "title": "",
                    "type": "",
                    "user": {
                        "userId": "",
                        "username": ""
                    }
                },
                "text": "",
                "timestamp": "",
                "likes": ""
            }
        ]
    }

    "comments.json" --o "pfps"
    "comments.json" --o "covers"
}
@enduml
