@startuml getCommentsOfPost-Request
!theme toy
skinparam linetype ortho
title "getCommentsOfPost /api/comments GET Request"

json Data {
    "limit": "",
    "offset": ""
}

note bottom of Data 
    By chunks: **limit**, **offset** required.
end note
@enduml
@startuml getCommentsOfPost-Response
!theme toy
skinparam linetype ortho
title "getCommentsOfPost /api/comments GET Response"

package "comments.zip" {

    folder "pfps" {
        file "userId-pfp.png"
    }

    json "comments.json" {
        "comments": [
            {
                "commentId": "",
                "user": {
                    "userId": "",
                    "username": ""
                },
                "text": "",
                "timestamp": "",
                "likes": ""
            }
        ]
    }

    "comments.json" --o "pfps"
}
@enduml
