@startuml deleteContributionComment-Request
!theme toy
title "deleteContributionComment /api/contributionComments/{contributionCommentId} DELETE Request"

json Auth {
    "sub": "",
    "iat": "",
    "exp": ""
}
@enduml
@startuml deleteContributionComment-Response
!theme toy
title "deleteContributionComment /api/contributionComments/{contributionCommentId} DELETE Response"
@enduml
