@startuml removeDislikeFromContribution-Request
!theme toy
title "removeDislikeFromContribution /api/contributionDislikes/{contributionDislikeId} DELETE Request"

json Auth {
    "sub": "",
    "iat": "",
    "exp": ""
}
@enduml
@startuml removeDislikeFromContribution-Response
!theme toy
title "removeDislikeFromContribution /api/contributionDislikes/{contributionDislikeId} DELETE Response"
@enduml
