@startuml searchUsersWhoLandedTrick-Request
!theme toy
skinparam linetype ortho
title "searchUsersWhoLandedTrick /api/tricks GET Request"

json Data {
    "name": "",
    ' Optional
    "filter": {
        "spot": ""
    },
    "orderBy": "",
    "limit": "",
    "offset": ""
}

note top of Data
    Optional fields: **filter**
end note

note bottom of Data
    By chunks: **limit**, **offset** required
end note
@enduml

@startuml searchUsersWhoLandedTrick-Response
!theme toy
skinparam linetype ortho
title "searchUsersWhoLandedTrick /api/tricks GET Response"

package "users.zip" {

    folder "pfps" {
        file "userId-pfp.png"
    }

    json "tricks.json" {
        "tricks": [
            {
                "trickId": "",
                "user": {
                    "userId": "",
                    "username": ""
                },
                ' Name is already known to the client.
                "points": "",
                "spots": [
                    {
                        "spot": "",
                        "date": ""
                    }
                ]
            }
        ]
    }

    "tricks.json" --o "pfps"
    
    note right of "tricks.json"
        The name of the trick is
        already known to the client
    end note
}

@enduml
