@startuml likeAComment-Request
!theme toy
skinparam linetype ortho
title "likeAComment /api/commentLikes POST Request"

json Data {
    "commentId": ""
}

json Auth {
    "sub": "",
    "iat": "",
    "exp": ""
}

Data --* Auth
@enduml
@startuml likeAComment-Response
!theme toy
title "likeAComment /api/commentLikes POST Response"

json Data {
    "commentLikeId": ""
}
@enduml
