@startuml getFriendshipRequestsToUser-Request
!theme toy
skinparam linetype ortho
title "getFriendshipRequestsToUser /api/friendshipRequests/to GET Request"

json Auth {
    "sub": "",
    "iat": "",
    "exp": ""
}
@enduml
@startuml getFriendshipRequestsToUser-Response
!theme toy
skinparam linetype ortho
title "getFriendshipRequestsToUser /api/friendshipRequests/to GET Response"

package "friendshipRequests.zip" {

    folder "pfps" {
        file "userId-pfp.png"
    }

    json "friendshipRequests.json" {
        "friendshipRequests": [
            {
                "friendshipRequestId": "",
                "toUser": {
                    "userId": "",
                    "username": ""
                },
                "timestamp": ""
            }
        ]
    }

    "friendshipRequests.json" --o "pfps"
}
@enduml