@startuml updateMusic-Request
!theme toy
title "updateMusic /api/posts/:postId PATCH Request"

package "postUpdate.zip" {
    ' Optional (cover replacement)
    file "postId-cover.png"

    ' Optional (audio replacement)
    file "postId.mp3"

    json "postUpdate.json" {
        ' Optional
        "title": "",
        ' Optional
        "description": "",
        ' Optional
        ' If omitted, no changes are made.
        ' If present, adds the new ones and removes all the missing ones
        "tags": [],
        ' Optional
        ' If omitted, no changes are made.
        ' If present, adds the new ones and removes all the missing ones
        "partecipants": [
            {
                ' Optional
                "role": "",
                "userId": ""
            }
        ]
    }
}

json Auth {
    "sub": "",
    "iat": "",
    "exp": ""
}
@enduml
@startuml updateMusic-Response
!theme toy
title "updateMusic /api/posts/:postId PATCH Response"
@enduml
