@startuml refuseFriendshipRequest-Request
!theme toy
title "refuseFriendshipRequest /api/friendshipRequests/:friendshipRequestId DELETE Request"

json Auth {
    "sub": "",
    "iat": "",
    "exp": ""
}
@enduml
@startuml refuseFriendshipRequest-Response
!theme toy
title "refuseFriendshipRequest /api/friendshipRequests/:friendshipRequestId DELETE Response"
@enduml
