@startuml updateContribution-Request
!theme toy
skinparam linetype ortho
title "updateContribution /api/contributions/:contributionId PATCH Request"

json Data {
    ' Optional
    "title": "",
    ' Optional
    "text": "",
    ' Optional
    "tags": ""
}

note bottom of Data
    Optional fields: **title**, **text**, **tags**
end note

json Auth {
    "sub": "",
    "iat": "",
    "exp": ""
}

Data --* Auth
@enduml
@startuml updateContribution-Response
!theme toy
title "updateContribution /api/contributions/:contributionId PATCH Response"
@enduml
